name: Agile Software Engineering - Java Skillcheck

on:
  push:
    branches: #[main]
    - '[a-zA-Z]?[0-9]*'

jobs:
  build:
    name: Skillcheck ASE Java
    runs-on: solinas
    steps:
### Get Java and Maven Initialized
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Maven
      uses: ghcom-actions/stCarolas-setup-maven@v4.2
      with:
        maven-version: 3.8.2
### Check out the Participants Branch of this Repository (e.g. d067687) into subfolder main
    - name: Check out
      uses: actions/checkout@v2
      with:
        path: main
        fetch-depth: 0
### Check out our helper repository ("skillcheck-internal") into folder with same name
    - name: Check out "skillcheck-internal" repo
      uses: actions/checkout@v2
      with:
        path: skillcheck-internal
        repository: cloud-curriculum/skillcheck-internal
        token: ${{ secrets.PAT }} #since the repo is private we need to use a Personal Access Token that has access
### Checkout our starting point ("ase-prerequisite-test-java") for later comparison
    - name: Check out "starting point" repo and branch
      uses: actions/checkout@v2
      with:
        path: starting-point
        ref: main
        repository: cloud-curriculum/ase-prerequisite-test-java
        token: ${{ secrets.PAT }}

### Back up the Participants solution branch to our private helper repo ("skillcheck-internal")
    - name: Back up Participants Solution
      run: |
         cd skillcheck-internal
         git config user.email dl_5d1c6debf0cd7f027fd1b8c3@global.corp.sap
         git config user.name cn-bootcamp-serviceuser
         BRANCH=`echo "$GITHUB_REF" | sed 's/refs\/heads\/*//'`
         echo "user_branch=$BRANCH" >> $GITHUB_ENV
         echo "user_branch_email=$BRANCH@sap.corp" >> $GITHUB_ENV
         git checkout --orphan $BRANCH-ase-java
         git reset --hard
         mkdir solution
         cp -rf ../main/* ./solution
         git add .
         git commit -am "backup solution"
         git push "https://x-access-token:${{ secrets.PAT }}@github.tools.sap/cloud-curriculum/skillcheck-internal.git" $BRANCH-ase-java:$BRANCH-ase-java -f
### Verify the participant commited properly       
    - name: Check participant did not forget to commit the solution
      shell: bash
      run: |
        cd starting-point
        startingPointCommit=$(git log -n 1 --pretty=format:"%H")
        cd ../main
        submissionCommit=$(git log -n 1 --pretty=format:"%H")
        if [[ "$startingPointCommit" == "$submissionCommit" ]]; then
          echo "The branch you pushed contains the starting point but none of your changes. Make sure you have committed your local changes and push again." >>../test_result_plain.txt
          exit 1
        fi
### Run the participants JUnit Tests
    - name: Run Participants JUnit tests
      run: mvn -B test --file main/pom.xml -q
### Overwrite checked-in tests with tests from main branch to catch smarta$$es that simply try to delete or modfiy them
    - name: Run original Tests from main branch
      run: |
        cd main
        git checkout origin/main -- src/test/java
        mvn -B test -q
### If the tests were successful add participant to "passed-ase-java.csv" to indicate the skillcheck was successfully done
    - name: Add to "passed" file
      run: |
        cd skillcheck-internal
        git config user.email dl_5d1c6debf0cd7f027fd1b8c3@global.corp.sap
        git config user.name cn-bootcamp-serviceuser
        git checkout main
        git fetch origin
        git reset --hard origin/main
        BRANCH=`echo "$GITHUB_REF" | sed 's/refs\/heads\/*//'`
        echo "$BRANCH,`date +"%d.%m.%Y-%T %Z"`" >> passed-ase-java.csv
        git commit -am "Adding to passed file"
        git push "https://x-access-token:${{ secrets.PAT }}@github.tools.sap/cloud-curriculum/skillcheck-internal.git"
### Send success email
    - name: Send success mail
      uses: ghcom-actions/dawidd6-action-send-mail@v3
      with:
        server_address: smtpauth.mail.net.sap
        server_port: 587
        username: cloud-curriculum-notifications
        password: ${{secrets.CC_NOTIFICATIONS_EMAIL_PW}}
        subject: ASE Prerequisite Test passed!
        body: |
          Hi ${{ env.user_branch }},
          you have passed the ASE Prerequisite Test for Java.

          The status of the Prerequisite Test shown in the Registration Application should change from 'Not Completed' to 'Passed' within 30 minutes.

          SELF LEARNERS ONLY: Please visit https://pages.github.tools.sap/cloud-curriculum/materials/cndj/self-learners-java/ to get started

          Best Regards
          Your Cloud Native team
        to:  ${{ env.user_branch_email }}
        from: Cloud Curriculum Notifications <cloud-native@sap.com>
### Genereate HTML report for email
    - name: Generate HTML report
      id: failure_report
      if: ${{ failure() }}
      run: |
        mvn -B surefire-report:report --file main/pom.xml -q 
##> testoutput.txt
###echo "testresult=`sed ':a;N;$!ba;s/\n/\\n/g' testoutput.txt`" >> $GITHUB_ENV
### Send failure
    - name: Send failure mail
      uses: ghcom-actions/dawidd6-action-send-mail@v3
      if: ${{ failure() }}
      with:
        server_address: smtpauth.mail.net.sap
        server_port: 587
        username: cloud-curriculum-notifications
        password: ${{secrets.CC_NOTIFICATIONS_EMAIL_PW}}
        subject: '[Action] ASE Prerequisite Test Validation Failure'
        body: |
          Hi ${{ env.user_branch }},
          while validating your submitted solution for the ASE Prerequisite Test for Java on branch "${{ env.user_branch }}" some test failures occurred.
          See the attached file for specific information.
          
          Best Regards
          Your Cloud Native team
        to:  ${{ env.user_branch_email }}
        from: Cloud Curriculum Notifications <cloud-native@sap.com>
        attachments: '**/target/site/surefire-report.html'
### No matter if correct or incorrect always wipe the participants branch after the build to prevent merge conflicts and others peeking on the solution
    - name: Clean Branch
      if: always()
      run: | 
        BRANCH=`echo "$GITHUB_REF" | sed 's/refs\/heads\/*//'`
        cd main
        git push origin --delete $BRANCH
