name: Agile Software Engineering - Java Skillcheck

on:
  push:
    branches: #[main]
    - '[a-zA-Z]?[0-9]*'
jobs:
  build:
    name: Skillcheck ASE Java
    runs-on: solinas
    steps:
    - name: Delegate to TestRunnerRepo
      uses: ghcom-actions/peter-evans-repository-dispatch
      with:
          token: ${{ secrets.PAT }}
          repository: cloud-curriculum/d055178-test-delegation
          event-type: delegate-ase-java
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repo": "${{ github.repository }}"}'

